/**
 * The Development Edge rule catalog (Phase 7A proposal §5, ADR-0051).
 *
 * Mirrors `private.edge_rules()` in
 * supabase/migrations/20261006000000_phase7a_edge_catalog.sql; rules.test.ts
 * checks that the two agree. The database is the authority for when a rule
 * holds; this module carries the words a person reads.
 */

export const EDGE_LENSES = [
  "integrity",
  "realization",
  "change",
  "exposure",
  "potential",
  "learning",
] as const;
export type EdgeLens = (typeof EDGE_LENSES)[number];

export const EDGE_LENS_LABELS: Record<EdgeLens, string> = {
  integrity: "Integrity",
  realization: "Realization",
  change: "Change",
  exposure: "Exposure",
  potential: "Potential",
  learning: "Learning",
};

/** `suggested` is reserved for Phase 7B and never produced in 7A. */
export const EPISTEMIC_STATUSES = ["recorded", "derived", "worth_considering"] as const;
export type EpistemicStatus = (typeof EPISTEMIC_STATUSES)[number];
export const RESERVED_EPISTEMIC_STATUSES = ["suggested"] as const;

export const EPISTEMIC_LABELS: Record<EpistemicStatus, string> = {
  recorded: "Recorded",
  derived: "Derived",
  worth_considering: "Worth considering",
};

export const EPISTEMIC_DEFINITIONS: Record<EpistemicStatus, string> = {
  recorded: "A fact the team recorded, read back as it stands.",
  derived: "A correspondence between governed records, calculated by a fixed rule.",
  worth_considering: "A pattern in the records that may warrant a look. It does not claim a cause.",
};

export const EDGE_HOMES = [
  "intelligence",
  "implementation",
  "architecture",
  "review",
  "deliverable",
  "criteria",
  "practice",
] as const;
export type EdgeHome = (typeof EDGE_HOMES)[number];

export const EDGE_SUBJECT_TYPES = [
  "element",
  "client_action",
  "method_application",
  "acceptance_criterion",
  "engagement",
] as const;
export type EdgeSubjectType = (typeof EDGE_SUBJECT_TYPES)[number];

export const TRIGGER_TYPES = [
  "substantive_revision",
  "status_change",
  "evidence_link",
  "decision",
  "date",
  "state",
] as const;
export type TriggerType = (typeof TRIGGER_TYPES)[number];

export const TIME_BASES = ["system_time", "exact_version", "business_date", "none"] as const;
export type TimeBasis = (typeof TIME_BASES)[number];

export const LIST_TIERS = ["ambient", "attention"] as const;
export type ListTier = (typeof LIST_TIERS)[number];

/** Governance acts that would make a condition stop holding (reconciliation §27). */
export const RESOLVING_ACTS = {
  revise_statement_or_validate: "Revise the statement and publish, or record the assumption's validation status",
  retire_or_repoint_relationship: "Retire or re-point the relationship",
  retire_conflict_or_judge: "Retire the relationship with a reason, or record that the tension is accepted",
  record_method_lineage: "Record the method lineage, or publish with corrected provenance",
  relate_metric: "Relate a Metric, or record your judgment",
  relate_outcome: "Relate it to an Intended Outcome, or record your judgment",
  relate_governance: "Relate a holder or a governed element, or record your judgment",
  create_pathway: "Create an initiative that implements it, or relate an operating form",
  validate_through_review: "Record a validation through a held Review",
  repoint_implements: "Re-point or retire the implements relationship, or change the initiative's status",
  review_after_revision: "Hold a Review that examines the revised version, or record your judgment",
  link_realization_evidence: "Link evidence to the initiative or to an achieved checkpoint",
  achieve_or_retarget_checkpoint: "Achieve the checkpoint or record a new target",
  schedule_review: "Schedule a Review that examines it",
  supersede_criterion: "Supersede the criterion with a newly agreed one, or record your judgment",
  later_review: "Hold a later Review that examines the element, or record your judgment",
  revise_affected_element: "Publish a revision of the affected element, or record that it needs none",
  new_deliverable_version: "Publish a new Deliverable version and record its approval, or record your judgment",
  handle_contribution: "Handle the contribution",
  none_required_method: "None required: pins are deliberate. Record your judgment, or change the engagement's release",
  request_latest_approval: "Request and record approval of the latest version",
  satisfy_dependency: "Satisfy or re-scope a dependency, or record your judgment",
  resolve_escalation_or_hold: "Resolve the escalation, or hold the Review with the risk on its agenda",
  revise_threatened: "Revise the threatened architecture, retire the relationship, or close the risk",
  decide_pursuit: "Decide how to pursue it, or record your judgment",
  relate_carrier: "Relate a carrier, or change the opportunity's status",
  examine_architecture: "None required. Examine the architecture, or record your judgment",
  record_outputs: "Record the output through ordinary operations, or record an addendum explaining it",
  link_gathered_evidence: "Link gathered evidence, or record an addendum",
  validate_assumption: "Validate or invalidate the assumption",
  revise_underpinned: "Revise or retire the underpinned architecture",
  relate_mitigation: "Relate a mitigation",
  record_decision: "Record the decision or a new needed-by date",
  update_opportunity: "Update the opportunity's status",
  review_record: "Review the record and set the next date",
  follow_up_action: "Follow up the action",
  triage_record: "Triage the record",
  retarget_initiative: "Record a new target or the initiative's status",
  examine_reached: "Examine the reached record, publish its own revision, or record your judgment",
} as const;
export type ResolvingAct = keyof typeof RESOLVING_ACTS;

export type EdgeRule = {
  key: string;
  candidate: string;
  origin: "existing" | "new";
  home: EdgeHome;
  lens: EdgeLens;
  epistemicStatus: EpistemicStatus;
  subjectType: EdgeSubjectType;
  scope: string;
  triggerType: TriggerType;
  timeBasis: TimeBasis;
  substantiveOnly: boolean;
  listTier: ListTier;
  resolvingAct: ResolvingAct;
  thresholds: string | null;
  /** What makes the item this item; a change brings a judged item back (§5.4). */
  fingerprint: string;
  label: string;
  definition: string;
  why: string;
};

/**
 * Every rule, in catalog order: the 31 new rules (§5.2), then the 11 Phase 4
 * and Phase 5 rules consumed unchanged (§5.3).
 */
export const EDGE_RULES: readonly EdgeRule[] = [
  // Integrity ------------------------------------------------------------------
  {
    key: "statement_contradicted_by_evidence",
    candidate: "D-03",
    origin: "new",
    home: "architecture",
    lens: "integrity",
    epistemicStatus: "derived",
    subjectType: "element",
    scope: "Published element with a statement carrying contradicting evidence",
    triggerType: "evidence_link",
    timeBasis: "system_time",
    substantiveOnly: false,
    listTier: "ambient",
    resolvingAct: "revise_statement_or_validate",
    thresholds: null,
    fingerprint: "The sorted ids of the contradicting evidence links",
    label: "Evidence contradicts a statement",
    definition: "A published statement on this element cites evidence recorded as contradicting it.",
    why: "A claim the architecture rests on has evidence against it. It may warrant examination.",
  },
  {
    key: "relationship_to_replaced_element",
    candidate: "D-05",
    origin: "new",
    home: "architecture",
    lens: "integrity",
    epistemicStatus: "derived",
    subjectType: "element",
    scope: "Live element with an unretired relationship to a superseded or retired element",
    triggerType: "state",
    timeBasis: "none",
    substantiveOnly: false,
    listTier: "attention",
    resolvingAct: "retire_or_repoint_relationship",
    thresholds: null,
    fingerprint: "The relationship ids with the replaced end and its lifecycle",
    label: "Relationship to a replaced element",
    definition: "A live element is still related to an element that has been superseded or retired.",
    why: "The design may be pointing at something the architecture no longer holds.",
  },
  {
    key: "conflict_unresolved",
    candidate: "D-06",
    origin: "new",
    home: "architecture",
    lens: "integrity",
    epistemicStatus: "recorded",
    subjectType: "element",
    scope: "Unretired conflicts_with between two published elements",
    triggerType: "state",
    timeBasis: "none",
    substantiveOnly: false,
    listTier: "attention",
    resolvingAct: "retire_conflict_or_judge",
    thresholds: null,
    fingerprint: "The conflicts_with relationship id",
    label: "Recorded tension",
    definition: "Two published elements are recorded as in tension with each other.",
    why: "A recognized tension stays open until someone resolves it or accepts it.",
  },
  {
    key: "methodology_derived_without_model",
    candidate: "D-08",
    origin: "new",
    home: "architecture",
    lens: "integrity",
    epistemicStatus: "recorded",
    subjectType: "element",
    scope: "Live element or statement with methodology-derived provenance and no instantiates lineage",
    triggerType: "state",
    timeBasis: "none",
    substantiveOnly: false,
    listTier: "attention",
    resolvingAct: "record_method_lineage",
    thresholds: null,
    fingerprint: "The ids of the element and statements recorded as methodology-derived",
    label: "Methodology-derived without its model",
    definition: "Content is recorded as derived from the methodology, but names no Model it instantiates.",
    why: "Provenance that names the method should say which part of the method it came from.",
  },
  {
    key: "measurement_gap",
    candidate: "D-09",
    origin: "new",
    home: "architecture",
    lens: "integrity",
    epistemicStatus: "derived",
    subjectType: "element",
    scope: "Published Intended Outcome without measured_by, or published Metric that measures nothing",
    triggerType: "state",
    timeBasis: "none",
    substantiveOnly: false,
    listTier: "ambient",
    resolvingAct: "relate_metric",
    thresholds: null,
    fingerprint: "The variant",
    label: "Measurement gap",
    definition: "An Intended Outcome has no Metric, or a Metric measures nothing.",
    why: "Without a measure, no one can observe whether the outcome is being reached.",
  },
  {
    key: "capability_serves_no_outcome",
    candidate: "D-10",
    origin: "new",
    home: "architecture",
    lens: "integrity",
    epistemicStatus: "derived",
    subjectType: "element",
    scope: "Published Capability that serves no Intended Outcome, directly or through its part_of ancestors",
    triggerType: "state",
    timeBasis: "none",
    substantiveOnly: false,
    listTier: "attention",
    resolvingAct: "relate_outcome",
    thresholds: null,
    fingerprint: "Constant: the condition itself",
    label: "Capability serves no outcome",
    definition: "A published Capability serves no Intended Outcome, directly or through what it is part of.",
    why: "A capability with no outcome to serve may be unexplained in the architecture.",
  },
  {
    key: "governance_allocation_gap",
    candidate: "D-11",
    origin: "new",
    home: "architecture",
    lens: "integrity",
    epistemicStatus: "derived",
    subjectType: "element",
    scope: "Published Decision Right with no holder, or published Governance Body that governs nothing",
    triggerType: "state",
    timeBasis: "none",
    substantiveOnly: false,
    listTier: "attention",
    resolvingAct: "relate_governance",
    thresholds: "body_governs_nothing is Ambient only (narrowed)",
    fingerprint: "The variant",
    label: "Governance allocation gap",
    definition: "A Decision Right has no holder, or a Governance Body governs nothing.",
    why: "Authority that no one holds, or a body with nothing to govern, leaves governance unallocated.",
  },
  // Realization ----------------------------------------------------------------
  {
    key: "approved_without_pathway",
    candidate: "D-12",
    origin: "new",
    home: "architecture",
    lens: "realization",
    epistemicStatus: "derived",
    subjectType: "element",
    scope:
      "Published Capability or Application Format with no implements on it or its part_of descendants (depth 2), and for a Capability no implemented_through",
    triggerType: "state",
    timeBasis: "none",
    substantiveOnly: false,
    listTier: "attention",
    resolvingAct: "create_pathway",
    thresholds: "part_of descendants to depth 2",
    fingerprint: "Constant: the condition itself",
    label: "No pathway to realization",
    definition: "Published design has no initiative implementing it and no operating form.",
    why: "Design without a realization pathway may stay on paper.",
  },
  {
    key: "operational_not_validated",
    candidate: "D-13",
    origin: "new",
    home: "implementation",
    lens: "realization",
    epistemicStatus: "recorded",
    subjectType: "element",
    scope: "Live initiative with status operational and no validates",
    triggerType: "status_change",
    timeBasis: "system_time",
    substantiveOnly: false,
    listTier: "attention",
    resolvingAct: "validate_through_review",
    thresholds: null,
    fingerprint: "The status history row that made it operational",
    label: "Operational, not yet validated",
    definition: "The initiative is recorded as operational and no Review has validated it.",
    why: "Operation is not validation. A held Review closes the loop.",
  },
  {
    key: "implements_replaced_element",
    candidate: "D-14",
    origin: "new",
    home: "implementation",
    lens: "realization",
    epistemicStatus: "derived",
    subjectType: "element",
    scope: "Live initiative that implements a superseded or retired element",
    triggerType: "state",
    timeBasis: "none",
    substantiveOnly: false,
    listTier: "attention",
    resolvingAct: "repoint_implements",
    thresholds: null,
    fingerprint: "The replaced elements and their lifecycle",
    label: "Implements a replaced element",
    definition: "The initiative implements an element that has been superseded or retired.",
    why: "Reality may be realizing a design the architecture has replaced.",
  },
  {
    key: "implemented_element_revised",
    candidate: "D-15",
    origin: "new",
    home: "implementation",
    lens: "realization",
    epistemicStatus: "derived",
    subjectType: "element",
    scope:
      "Initiative not started, in progress, stalled or operational whose implemented element was substantively revised after implements was recorded",
    triggerType: "substantive_revision",
    timeBasis: "system_time",
    substantiveOnly: true,
    listTier: "attention",
    resolvingAct: "review_after_revision",
    thresholds: null,
    fingerprint: "The implemented element and its latest substantive version",
    label: "Implemented design was revised",
    definition: "The element this initiative implements was substantively revised after implementation began.",
    why: "Reality may be tracking the earlier design.",
  },
  {
    key: "validated_element_revised",
    candidate: "D-16",
    origin: "new",
    home: "implementation",
    lens: "realization",
    epistemicStatus: "derived",
    subjectType: "element",
    scope: "Validated initiative whose implemented element was substantively revised after the validation",
    triggerType: "substantive_revision",
    timeBasis: "system_time",
    substantiveOnly: true,
    listTier: "attention",
    resolvingAct: "review_after_revision",
    thresholds: null,
    fingerprint: "The implemented element and its latest substantive version",
    label: "Validated design was revised",
    definition: "The element this validated initiative implements was substantively revised after the validation.",
    why: "The validation judged an earlier design.",
  },
  {
    key: "realization_without_evidence",
    candidate: "D-17",
    origin: "new",
    home: "implementation",
    lens: "realization",
    epistemicStatus: "derived",
    subjectType: "element",
    scope: "Operational or validated initiative with no evidence link and no checkpoint achieved with evidence",
    triggerType: "state",
    timeBasis: "none",
    substantiveOnly: false,
    listTier: "attention",
    resolvingAct: "link_realization_evidence",
    thresholds: null,
    fingerprint: "The initiative's status",
    label: "Realization without evidence",
    definition: "The initiative is recorded as operational or validated, and no evidence is cited for it.",
    why: "A realization claim rests on the team's word alone.",
  },
  {
    key: "checkpoint_past_target",
    candidate: "D-19",
    origin: "new",
    home: "implementation",
    lens: "realization",
    epistemicStatus: "recorded",
    subjectType: "element",
    scope: "Live initiative with a checkpoint not achieved whose target is before the business date",
    triggerType: "date",
    timeBasis: "business_date",
    substantiveOnly: false,
    listTier: "attention",
    resolvingAct: "achieve_or_retarget_checkpoint",
    thresholds: null,
    fingerprint: "The checkpoint and its target date",
    label: "Checkpoint past its target",
    definition: "A checkpoint's target date has passed and it is not recorded as achieved.",
    why: "The plan and the record have diverged.",
  },
  {
    key: "criteria_without_review_path",
    candidate: "D-20",
    origin: "new",
    home: "implementation",
    lens: "realization",
    epistemicStatus: "derived",
    subjectType: "element",
    scope: "Live initiative with agreed criteria in force and no scheduled or held Review examining it or what it implements",
    triggerType: "state",
    timeBasis: "none",
    substantiveOnly: false,
    listTier: "attention",
    resolvingAct: "schedule_review",
    thresholds: null,
    fingerprint: "The criteria in force",
    label: "Criteria with no Review to judge them",
    definition: "Criteria are agreed for this initiative, and no Review is set to examine it.",
    why: "Agreed criteria are judged only through a held Review.",
  },
  // Change ---------------------------------------------------------------------
  {
    key: "criteria_predate_revision",
    candidate: "D-04",
    origin: "new",
    home: "criteria",
    lens: "change",
    epistemicStatus: "derived",
    subjectType: "acceptance_criterion",
    scope:
      "Agreed criterion in force whose governed element was substantively revised after agreed_recorded_at; no item when the agreement time was not recorded",
    triggerType: "substantive_revision",
    timeBasis: "system_time",
    substantiveOnly: true,
    listTier: "attention",
    resolvingAct: "supersede_criterion",
    thresholds: null,
    fingerprint: "The governed element's latest substantive version",
    label: "Criterion agreed before a revision",
    definition: "The element this criterion governs was substantively revised after the criterion was agreed.",
    why: "The agreed criterion may describe an earlier design.",
  },
  {
    key: "examined_element_revised_since_review",
    candidate: "D-21",
    origin: "new",
    home: "review",
    lens: "change",
    epistemicStatus: "derived",
    subjectType: "element",
    scope:
      "Held Review whose captured examined version is behind a later substantive version; Reviews held before 7A only through their frozen baseline",
    triggerType: "substantive_revision",
    timeBasis: "exact_version",
    substantiveOnly: true,
    listTier: "attention",
    resolvingAct: "later_review",
    thresholds: null,
    fingerprint: "The examined element and its latest substantive version",
    label: "Examined element revised since the Review",
    definition: "An element this Review examined has a substantive revision later than the version it examined.",
    why: "The Review's judgment predates the revision.",
  },
  {
    key: "evidence_after_review",
    candidate: "D-22",
    origin: "new",
    home: "review",
    lens: "change",
    epistemicStatus: "derived",
    subjectType: "element",
    scope: "Held Review with a capture, where evidence was linked to a captured element after the capture",
    triggerType: "evidence_link",
    timeBasis: "system_time",
    substantiveOnly: false,
    listTier: "ambient",
    resolvingAct: "later_review",
    thresholds: "Attention when any link contradicts; Ambient otherwise",
    fingerprint: "The sorted ids of the evidence links",
    label: "Evidence arrived after the Review",
    definition: "Evidence was cited on an element this Review examined, after the Review was held.",
    why: "The Review did not have this evidence.",
  },
  {
    key: "decision_not_reflected",
    candidate: "D-23",
    origin: "new",
    home: "intelligence",
    lens: "change",
    epistemicStatus: "derived",
    subjectType: "element",
    scope: "Decided decision recorded after the latest content version of an element it affects",
    triggerType: "decision",
    timeBasis: "system_time",
    substantiveOnly: true,
    listTier: "attention",
    resolvingAct: "revise_affected_element",
    thresholds: null,
    fingerprint: "The decision's version and the affected element's latest content version",
    label: "Decision not yet reflected",
    definition: "The decision was recorded after the latest content version of an element it affects.",
    why: "The architecture may not yet reflect what was decided.",
  },
  {
    key: "deliverable_documents_revised",
    candidate: "D-24",
    origin: "new",
    home: "deliverable",
    lens: "change",
    epistemicStatus: "derived",
    subjectType: "element",
    scope:
      "Live Deliverable documenting an element revised after the version in its baseline, or without a baseline, after its latest approval",
    triggerType: "substantive_revision",
    timeBasis: "exact_version",
    substantiveOnly: true,
    listTier: "attention",
    resolvingAct: "new_deliverable_version",
    thresholds: null,
    fingerprint: "The documented element and its latest substantive version",
    label: "Deliverable documents a revised element",
    definition: "An element this Deliverable documents was substantively revised after the Deliverable's reference point.",
    why: "The Deliverable may describe an earlier design.",
  },
  {
    key: "contribution_on_prior_version",
    candidate: "D-25",
    origin: "new",
    home: "intelligence",
    lens: "change",
    epistemicStatus: "derived",
    subjectType: "element",
    scope: "Unhandled client contribution made on a version that has since been substantively revised",
    triggerType: "substantive_revision",
    timeBasis: "exact_version",
    substantiveOnly: true,
    listTier: "attention",
    resolvingAct: "handle_contribution",
    thresholds: null,
    fingerprint: "The contribution and the element's latest substantive version",
    label: "Client input on an earlier version",
    definition: "A client contribution not yet handled was made on a version that has since been revised.",
    why: "The client was responding to content that has changed.",
  },
  {
    key: "method_basis_superseded",
    candidate: "D-26, D-27",
    origin: "new",
    home: "practice",
    lens: "change",
    epistemicStatus: "recorded",
    subjectType: "method_application",
    scope:
      "Open Method Application pinned to a superseded Method version; or open applications started under a DAM release that is not the engagement's or not the latest",
    triggerType: "state",
    timeBasis: "none",
    substantiveOnly: false,
    listTier: "ambient",
    resolvingAct: "none_required_method",
    thresholds: "pinned_version_superseded Ambient; release_moved Attention, one engagement-level item",
    fingerprint: "The pinned version, or the releases and the open applications",
    label: "Method basis has moved",
    definition: "Open method work rests on a Method version or DAM release that has since moved on.",
    why: "Pins are deliberate, but the practice basis under open work is worth knowing.",
  },
  {
    key: "approval_behind_published",
    candidate: "D-28",
    origin: "new",
    home: "architecture",
    lens: "change",
    epistemicStatus: "derived",
    subjectType: "element",
    scope: "Element whose latest approved version is behind its latest published version, with a substantive revision between",
    triggerType: "substantive_revision",
    timeBasis: "exact_version",
    substantiveOnly: true,
    listTier: "attention",
    resolvingAct: "request_latest_approval",
    thresholds: "Ambient while an approval request on the latest version is pending",
    fingerprint: "The approved version and the latest substantive version",
    label: "Approval is behind the published version",
    definition: "The client approved an earlier version, and the element has been substantively revised since.",
    why: "What was approved is not what is published.",
  },
  // Exposure -------------------------------------------------------------------
  {
    key: "dependencies_converge",
    candidate: "D-31",
    origin: "new",
    home: "intelligence",
    lens: "exposure",
    epistemicStatus: "derived",
    subjectType: "element",
    scope: "Live element that is the depended-on end of two or more blocking, unsatisfied dependencies",
    triggerType: "status_change",
    timeBasis: "system_time",
    substantiveOnly: false,
    listTier: "attention",
    resolvingAct: "satisfy_dependency",
    thresholds: "2 or more converging dependencies",
    fingerprint: "The sorted dependency ids with their statuses",
    label: "Dependencies converge",
    definition: "Several blocking dependencies wait on this element.",
    why: "Many paths through one point concentrate exposure.",
  },
  {
    key: "escalation_before_review",
    candidate: "D-32",
    origin: "new",
    home: "intelligence",
    lens: "exposure",
    epistemicStatus: "derived",
    subjectType: "element",
    scope: "Open escalation on a risk that threatens an element a scheduled Review examines",
    triggerType: "state",
    timeBasis: "none",
    substantiveOnly: false,
    listTier: "attention",
    resolvingAct: "resolve_escalation_or_hold",
    thresholds: "Always shown in the escalated tier, because an escalation is a human act",
    fingerprint: "The escalation and the scheduled Reviews",
    label: "Escalation before a Review",
    definition: "An escalated risk threatens something a scheduled Review will examine.",
    why: "The Review is where the team can take it up.",
  },
  {
    key: "materialized_risk_still_threatens",
    candidate: "D-33",
    origin: "new",
    home: "intelligence",
    lens: "exposure",
    epistemicStatus: "derived",
    subjectType: "element",
    scope: "Risk recorded as materialized with an unretired threatens to a live element",
    triggerType: "status_change",
    timeBasis: "system_time",
    substantiveOnly: false,
    listTier: "attention",
    resolvingAct: "revise_threatened",
    thresholds: null,
    fingerprint: "The threatened elements",
    label: "Materialized risk still bears on the design",
    definition: "The risk is recorded as materialized and still threatens live architecture.",
    why: "What the risk threatened has happened; the design may need to answer it.",
  },
  // Potential ------------------------------------------------------------------
  {
    key: "opportunity_advances_unrealized",
    candidate: "D-37",
    origin: "new",
    home: "intelligence",
    lens: "potential",
    epistemicStatus: "worth_considering",
    subjectType: "element",
    scope: "Open opportunity that advances a Capability or Application Format no initiative implements",
    triggerType: "state",
    timeBasis: "none",
    substantiveOnly: false,
    listTier: "attention",
    resolvingAct: "decide_pursuit",
    thresholds: null,
    fingerprint: "The advanced elements with no implementation",
    label: "Opportunity advances unrealized design",
    definition: "The opportunity would advance design that no initiative is realizing yet.",
    why: "Worth considering whether the opportunity and the realization plan belong together.",
  },
  {
    key: "opportunity_without_carrier",
    candidate: "D-39",
    origin: "new",
    home: "intelligence",
    lens: "potential",
    epistemicStatus: "derived",
    subjectType: "element",
    scope: "Opportunity being evaluated with no pursues from any capability, decision or recommendation",
    triggerType: "state",
    timeBasis: "none",
    substantiveOnly: false,
    listTier: "attention",
    resolvingAct: "relate_carrier",
    thresholds: null,
    fingerprint: "The opportunity's status",
    label: "Opportunity with no carrier",
    definition: "The opportunity is being evaluated, and nothing in the architecture pursues it.",
    why: "Evaluation without a carrier has nowhere to land.",
  },
  // Learning -------------------------------------------------------------------
  {
    key: "repeated_realization_difficulty",
    candidate: "D-40",
    origin: "new",
    home: "implementation",
    lens: "learning",
    epistemicStatus: "worth_considering",
    subjectType: "element",
    scope: "Element whose implementing initiatives record two or more transitions into stalled or abandoned, or reopenings",
    triggerType: "status_change",
    timeBasis: "system_time",
    substantiveOnly: false,
    listTier: "attention",
    resolvingAct: "examine_architecture",
    thresholds: "2 or more difficulties",
    fingerprint: "The counted status history rows",
    label: "Realization has been difficult",
    definition: "Initiatives realizing this element have stalled, been abandoned or reopened more than once.",
    why: "Worth examining. Recurrence is not a cause.",
  },
  {
    key: "application_outputs_absent",
    candidate: "D-41",
    origin: "new",
    home: "practice",
    lens: "learning",
    epistemicStatus: "derived",
    subjectType: "method_application",
    scope: "Completed Method Application with a declared output that has no produced link",
    triggerType: "state",
    timeBasis: "none",
    substantiveOnly: false,
    listTier: "attention",
    resolvingAct: "record_outputs",
    thresholds: null,
    fingerprint: "The declared outputs with no produced element",
    label: "Declared outputs not recorded",
    definition: "The Method declares outputs this completed application did not record as produced.",
    why: "The practice record is incomplete, or the output was not produced.",
  },
  {
    key: "application_instrument_evidence_absent",
    candidate: "D-42",
    origin: "new",
    home: "practice",
    lens: "learning",
    epistemicStatus: "derived",
    subjectType: "method_application",
    scope: "Completed or discontinued Method Application whose Method declares an Instrument no gathered evidence cites",
    triggerType: "state",
    timeBasis: "none",
    substantiveOnly: false,
    listTier: "attention",
    resolvingAct: "link_gathered_evidence",
    thresholds: null,
    fingerprint: "The declared Instrument versions with no gathered evidence",
    label: "Instrument evidence not recorded",
    definition: "The Method declares an Instrument, and no gathered evidence cites it.",
    why: "The practice record does not show what the Instrument gathered.",
  },
  // Phase 4 and Phase 5 rules, consumed unchanged -------------------------------
  {
    key: "assumption_unvalidated_underpins_published",
    candidate: "D-02",
    origin: "existing",
    home: "intelligence",
    lens: "integrity",
    epistemicStatus: "derived",
    subjectType: "element",
    scope: "Live assumption, unvalidated or validating, underpinning published architecture",
    triggerType: "status_change",
    timeBasis: "none",
    substantiveOnly: false,
    listTier: "attention",
    resolvingAct: "validate_assumption",
    thresholds: null,
    fingerprint: "Validation status and the underpinned reference codes",
    label: "Unvalidated assumption underpins published architecture",
    definition: "An assumption not yet validated underpins published architecture.",
    why: "The published design holds only if the assumption is true.",
  },
  {
    key: "assumption_invalidated_still_underpins",
    candidate: "D-01",
    origin: "existing",
    home: "intelligence",
    lens: "integrity",
    epistemicStatus: "derived",
    subjectType: "element",
    scope: "Live assumption recorded as invalidated, still underpinning live architecture",
    triggerType: "status_change",
    timeBasis: "none",
    substantiveOnly: false,
    listTier: "attention",
    resolvingAct: "revise_underpinned",
    thresholds: null,
    fingerprint: "The underpinned reference codes",
    label: "Invalidated assumption still underpins",
    definition: "An assumption recorded as invalidated still underpins live architecture.",
    why: "The design rests on something the team found untrue.",
  },
  {
    key: "risk_high_without_mitigation",
    candidate: "D-29",
    origin: "existing",
    home: "intelligence",
    lens: "exposure",
    epistemicStatus: "derived",
    subjectType: "element",
    scope: "Live risk, open or mitigating, with no mitigates",
    triggerType: "state",
    timeBasis: "none",
    substantiveOnly: false,
    listTier: "attention",
    resolvingAct: "relate_mitigation",
    thresholds: "Severity 15 or more",
    fingerprint: "Probability and impact",
    label: "High risk without mitigation",
    definition: "A high-severity risk has nothing mitigating it.",
    why: "Exposure without a response.",
  },
  {
    key: "dependency_blocking_unsatisfied",
    candidate: "D-30",
    origin: "existing",
    home: "intelligence",
    lens: "exposure",
    epistemicStatus: "derived",
    subjectType: "element",
    scope: "Live blocking dependency, not satisfied, whose dependent end is published",
    triggerType: "status_change",
    timeBasis: "none",
    substantiveOnly: false,
    listTier: "attention",
    resolvingAct: "satisfy_dependency",
    thresholds: null,
    fingerprint: "The dependency status",
    label: "Blocking dependency unsatisfied",
    definition: "A blocking dependency is not satisfied.",
    why: "Published architecture waits on it.",
  },
  {
    key: "decision_past_needed_by",
    candidate: "D-36",
    origin: "existing",
    home: "intelligence",
    lens: "exposure",
    epistemicStatus: "recorded",
    subjectType: "element",
    scope: "Live decision, open or recommended",
    triggerType: "date",
    timeBasis: "business_date",
    substantiveOnly: false,
    listTier: "attention",
    resolvingAct: "record_decision",
    thresholds: null,
    fingerprint: "The needed-by date",
    label: "Decision past its needed-by date",
    definition: "The decision is still open after the date it was needed by.",
    why: "Work that waits on it may be waiting.",
  },
  {
    key: "opportunity_window_closing",
    candidate: "D-36",
    origin: "existing",
    home: "intelligence",
    lens: "potential",
    epistemicStatus: "recorded",
    subjectType: "element",
    scope: "Live opportunity, identified or evaluating",
    triggerType: "date",
    timeBasis: "business_date",
    substantiveOnly: false,
    listTier: "attention",
    resolvingAct: "decide_pursuit",
    thresholds: "Window closing within 30 days",
    fingerprint: "The window's closing date",
    label: "Opportunity window closing",
    definition: "The opportunity's window closes within 30 days.",
    why: "A decision on pursuit is due before the window closes.",
  },
  {
    key: "opportunity_window_closed",
    candidate: "D-36",
    origin: "existing",
    home: "intelligence",
    lens: "potential",
    epistemicStatus: "recorded",
    subjectType: "element",
    scope: "Live opportunity, drafts included, identified, evaluating or pursuing",
    triggerType: "date",
    timeBasis: "business_date",
    substantiveOnly: false,
    listTier: "attention",
    resolvingAct: "update_opportunity",
    thresholds: null,
    fingerprint: "The window's closing date",
    label: "Opportunity window closed",
    definition: "The opportunity's window has closed and its status has not changed.",
    why: "The record may no longer describe the opportunity.",
  },
  {
    key: "review_overdue",
    candidate: "D-36",
    origin: "existing",
    home: "intelligence",
    lens: "exposure",
    epistemicStatus: "recorded",
    subjectType: "element",
    scope: "Live record with a stewardship review date, not in a terminal status",
    triggerType: "date",
    timeBasis: "business_date",
    substantiveOnly: false,
    listTier: "attention",
    resolvingAct: "review_record",
    thresholds: null,
    fingerprint: "The next review date",
    label: "Stewardship review overdue",
    definition: "The record's next review date has passed.",
    why: "The team set a date to look again.",
  },
  {
    key: "client_action_overdue",
    candidate: "D-36",
    origin: "existing",
    home: "intelligence",
    lens: "exposure",
    epistemicStatus: "recorded",
    subjectType: "client_action",
    scope: "Open client action",
    triggerType: "date",
    timeBasis: "business_date",
    substantiveOnly: false,
    listTier: "attention",
    resolvingAct: "follow_up_action",
    thresholds: null,
    fingerprint: "The due date",
    label: "Client action overdue",
    definition: "A client action is open past its due date.",
    why: "The client may need a follow-up.",
  },
  {
    key: "record_untriaged",
    candidate: "D-36",
    origin: "existing",
    home: "intelligence",
    lens: "exposure",
    epistemicStatus: "recorded",
    subjectType: "element",
    scope: "Live record untriaged",
    triggerType: "date",
    timeBasis: "business_date",
    substantiveOnly: false,
    listTier: "attention",
    resolvingAct: "triage_record",
    thresholds: "Untriaged for more than 7 days",
    fingerprint: "When the stewardship row last changed",
    label: "Record not triaged",
    definition: "The record has not been triaged for more than 7 days.",
    why: "Triage sets its attention and next review.",
  },
  {
    key: "implementation_past_target",
    candidate: "D-18",
    origin: "existing",
    home: "implementation",
    lens: "realization",
    epistemicStatus: "recorded",
    subjectType: "element",
    scope: "Live initiative not started, in progress or operational",
    triggerType: "date",
    timeBasis: "business_date",
    substantiveOnly: false,
    listTier: "attention",
    resolvingAct: "retarget_initiative",
    thresholds: null,
    fingerprint: "The target operational date",
    label: "Initiative past its target",
    definition: "The initiative's target operational date has passed.",
    why: "The plan and the record have diverged.",
  },
];

/**
 * `change_reaches` is a consequence type, not a condition (§4.3, §10.5): a
 * substantive revision or invalidation reaches a record through the impact
 * matrix. It has no catalog row; its envelope attributes are fixed here and in
 * `public.edge_items`.
 */
export const CHANGE_REACHES = {
  key: "change_reaches",
  home: "architecture",
  lens: "change",
  epistemicStatus: "derived",
  listTier: "attention",
  resolvingAct: "examine_reached",
  label: "Reached by a change",
  definition: "A revision reached this record through the governed impact matrix.",
  why: "It may warrant examination because of the change.",
} as const;

export const NEW_RULE_KEYS = EDGE_RULES.filter((r) => r.origin === "new").map((r) => r.key);
export const EXISTING_RULE_KEYS = EDGE_RULES.filter((r) => r.origin === "existing").map((r) => r.key);

const BY_KEY = new Map<string, EdgeRule>(EDGE_RULES.map((r) => [r.key, r]));

export function edgeRule(key: string): EdgeRule | undefined {
  return BY_KEY.get(key);
}

/** The plain-language label for a rule or consequence key. */
export function edgeRuleLabel(key: string): string {
  if (key === CHANGE_REACHES.key) return CHANGE_REACHES.label;
  return BY_KEY.get(key)?.label ?? key.replaceAll("_", " ");
}

export function resolvingActLabel(act: string): string {
  return (RESOLVING_ACTS as Record<string, string>)[act] ?? act.replaceAll("_", " ");
}

/** Variant labels for rules with variants. */
export const VARIANT_LABELS: Record<string, string> = {
  outcome_unmeasured: "Intended Outcome with no Metric",
  metric_unattached: "Metric that measures nothing",
  decision_right_unheld: "Decision Right with no holder",
  body_governs_nothing: "Governance Body that governs nothing",
  pinned_version_superseded: "Pinned Method version superseded",
  release_moved: "DAM release moved",
};
